In [39]:
import pandas as pd
import numpy as np

In [40]:
#loading dataset
sms=pd.read_table("C:\Users\Yatharth Saxena\Downloads\Compressed\pycon-2016-tutorial-master\pycon-2016-tutorial-master\data\sms.tsv", header =None , names=['label','message'])

In [41]:
#number of entries in xml
sms.shape

(5572, 2)

In [42]:
#printing top 10 entries
sms.head(10)

label                                            message
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...
5  spam  FreeMsg Hey there darling it's been 3 week's n...
6   ham  Even my brother is not like to speak with me. ...
7   ham  As per your request 'Melle Melle (Oru Minnamin...
8  spam  WINNER!! As a valued network customer you have...
9  spam  Had your mobile 11 months or more? U R entitle...

In [43]:
#counting ham and spam entries
sms.label.value_counts()

ham     4825
spam     747
Name: label, dtype: int64

In [44]:
#creating a label, giving ham as 0(negative) and spam as 1(positive)
sms['label_num'] = sms.label.map({'ham':0,'spam':1})

In [45]:
sms.head(5)

label                                            message  label_num
0   ham  Go until jurong point, crazy.. Available only ...          0
1   ham                      Ok lar... Joking wif u oni...          0
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...          1
3   ham  U dun say so early hor... U c already then say...          0
4   ham  Nah I don't think he goes to usf, he lives aro...          0

In [46]:
#X is feature matrix and y is output matrix
X=sms.message
y=sms.label_num
print(X.shape)
print(y.shape)

(5572,)
(5572,)


In [47]:
#splitting training data and test data in 75% and 25% respectively
from sklearn.cross_validation import train_test_split
X_train, X_test, y_train, y_test= train_test_split(X,y, random_state=1)
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)


(4179,)
(1393,)
(4179,)
(1393,)


In [48]:
#from nltk.stem.snowball import SnowballStemmer
#stemmer =SnowballStemmer("english")
#for word in X:
#   for j in word.split(" "):
#      j=stemmer.stem(j)        
#print X_train.head(5)
#count vectorizer is tool used to learn vocabulary from the documents
from sklearn.feature_extraction.text import CountVectorizer
vect= CountVectorizer(stop_words='english')

In [49]:
X_train_dtm= vect.fit_transform(X_train)

In [50]:
#sparse matrix
X_train_dtm

<4179x7204 sparse matrix of type '<type 'numpy.int64'>'
	with 32467 stored elements in Compressed Sparse Row format>

In [51]:
X_test_dtm= vect.transform(X_test)
X_test_dtm

<1393x7204 sparse matrix of type '<type 'numpy.int64'>'
	with 9780 stored elements in Compressed Sparse Row format>

In [52]:
#naive bayes is used for vocabulary
from sklearn.naive_bayes import MultinomialNB
nb= MultinomialNB()

In [53]:
#fitting dtraining data in naive bayes
%time nb.fit(X_train_dtm, y_train)

Wall time: 7 ms


MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [54]:
#predicting output for test data
y_pred_class= nb.predict(X_test_dtm)

In [55]:
#calculating accuracy of output of test data
from sklearn import metrics
metrics.accuracy_score(y_test, y_pred_class)

0.9877961234745154

In [56]:
#confusion matricsshows number of wrong  and right predictions
metrics.confusion_matrix(y_test, y_pred_class)

array([[1201,    7],
       [  10,  175]], dtype=int64)

In [57]:
#logistic reggression
from sklearn.linear_model import LogisticRegression

In [58]:
#comparing with logistic regression
logreg=LogisticRegression()

In [59]:
%time logreg.fit(X_train_dtm, y_train)

Wall time: 133 ms


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [60]:
y_pred_class = logreg.predict(X_test_dtm)

In [61]:
metrics.accuracy_score(y_test,y_pred_class)

0.97989949748743721

In [62]:
X_train_tokens = vect.get_feature_names()
len(X_train_tokens)

7204

In [63]:
print X_train_tokens[0:50]

[u'00', u'000', u'008704050406', u'0121', u'01223585236', u'01223585334', u'0125698789', u'02', u'0207', u'02072069400', u'02073162414', u'02085076972', u'021', u'03', u'04', u'0430', u'05', u'050703', u'0578', u'06', u'07', u'07008009200', u'07090201529', u'07090298926', u'07123456789', u'07732584351', u'07734396839', u'07742676969', u'0776xxxxxxx', u'07781482378', u'07786200117', u'078', u'07801543489', u'07808', u'07808247860', u'07808726822', u'07815296484', u'07821230901', u'07880867867', u'0789xxxxxxx', u'07946746291', u'0796xxxxxx', u'07973788240', u'07xxxxxxxxx', u'08', u'0800', u'08000407165', u'08000776320', u'08000839402', u'08000930705']


In [64]:
print X_train_tokens[-50:]

[u'yelling', u'yellow', u'yen', u'yeovil', u'yep', u'yer', u'yes', u'yest', u'yesterday', u'yetunde', u'yijue', u'ym', u'ymca', u'yo', u'yoga', u'yogasana', u'yor', u'yorge', u'youdoing', u'youi', u'youphone', u'youre', u'yourjob', u'youwanna', u'yowifes', u'yoyyooo', u'yr', u'yrs', u'ything', u'yummmm', u'yummy', u'yun', u'yunny', u'yuo', u'yuou', u'yup', u'zac', u'zaher', u'zealand', u'zebra', u'zed', u'zeros', u'zhong', u'zindgi', u'zoe', u'zoom', u'zouk', u'zyada', u'\xe8n', u'\u3028ud']


In [65]:
nb.feature_count_
#this matrix represents that how many times each of 7456 feature appeared in ham and in spam

array([[  0.,   0.,   0., ...,   1.,   1.,   1.],
       [  5.,  23.,   2., ...,   0.,   0.,   0.]])

In [66]:
nb.feature_count_.shape

(2, 7204)

In [67]:
ham_token_count = nb.feature_count_[0,:]
ham_token_count 

array([ 0.,  0.,  0., ...,  1.,  1.,  1.])

In [68]:
spam_token_count = nb.feature_count_[1,:]
spam_token_count 

array([  5.,  23.,   2., ...,   0.,   0.,   0.])

In [69]:
tokens= pd.DataFrame({'token':X_train_tokens, 'ham':ham_token_count,'spam':spam_token_count})

In [70]:
tokens.head(5)

ham  spam         token
0  0.0   5.0            00
1  0.0  23.0           000
2  0.0   2.0  008704050406
3  0.0   1.0          0121
4  0.0   1.0   01223585236

In [71]:
tokens.sample(5, random_state=6)

ham  spam    token
3488  1.0   0.0   iphone
488   0.0   2.0   450ppw
3585  9.0  13.0     join
2270  0.0   1.0  dontcha
1416  4.0   1.0   brings

In [72]:
nb.class_count_
#3617 - span
#562 - ham

array([ 3617.,   562.])

In [73]:
tokens['ham']=tokens.ham+1
tokens['spam']=tokens.spam+1
tokens.sample(5, random_state=6)

ham  spam    token
3488   2.0   1.0   iphone
488    1.0   3.0   450ppw
3585  10.0  14.0     join
2270   1.0   2.0  dontcha
1416   5.0   2.0   brings

In [74]:
tokens['ham']=tokens.ham / nb.class_count_[0]
tokens['spam']=tokens.spam / nb.class_count_[1]
tokens.sample(5,random_state=6)

ham      spam    token
3488  0.000553  0.001779   iphone
488   0.000276  0.005338   450ppw
3585  0.002765  0.024911     join
2270  0.000276  0.003559  dontcha
1416  0.001382  0.003559   brings

In [75]:
#calculating spamyness of each word
tokens['spam_ratio']=tokens.spam / tokens.ham
tokens.sample(5,random_state=6)

ham      spam    token  spam_ratio
3488  0.000553  0.001779   iphone    3.217972
488   0.000276  0.005338   450ppw   19.307829
3585  0.002765  0.024911     join    9.010320
2270  0.000276  0.003559  dontcha   12.871886
1416  0.001382  0.003559   brings    2.574377

In [76]:
#printing spammy words in decresing order
tokens.sort_values('spam_ratio',ascending=False)

ham      spam       token  spam_ratio
1718  0.000276  0.158363       claim  572.798932
5043  0.000276  0.135231       prize  489.131673
293   0.000276  0.087189        150p  315.361210
6470  0.000276  0.085409        tone  308.925267
3048  0.000276  0.076512  guaranteed  276.745552
307   0.000276  0.069395          18  251.001779
1971  0.000276  0.065836          cs  238.129893
7110  0.000553  0.129893         www  234.911922
246   0.000276  0.056940        1000  205.950178
1101  0.000276  0.053381     awarded  193.078292
297   0.000276  0.051601      150ppm  186.642349
6614  0.000553  0.099644          uk  180.206406
521   0.000276  0.048043         500  173.770463
5389  0.000276  0.044484    ringtone  160.898577
4244  0.000276  0.042705         mob  154.462633
1     0.000276  0.042705         000  154.462633
1785  0.000276  0.039146  collection  141.590747
336   0.000276  0.037367        2000  135.154804
6726  0.000276  0.037367       valid  135.154804
254   0.000276  0.037367         10p  135.154804
617   0.000276  0.037367         800  135.154804
620   0.000276  0.035587        8007  128.718861
302   0.000553  0.067616          16  122.282918
6922  0.000276  0.033808      weekly  122.282918
6471  0.000276  0.032028       tones  115.846975
3740  0.000276  0.032028        land  115.846975
3298  0.000276  0.032028        http  115.846975
522   0.000276  0.030249        5000  109.411032
4391  0.000276  0.030249    national  109.411032
5471  0.000276  0.030249         sae  109.411032
...        ...       ...         ...         ...
2170  0.011335  0.001779        didn    0.156974
1800  0.011612  0.001779      coming    0.153237
6876  0.023500  0.003559         wat    0.151434
2667  0.011888  0.001779        fine    0.149673
2970  0.012165  0.001779       gonna    0.146271
3760  0.012165  0.001779        late    0.146271
4573  0.024882  0.003559          oh    0.143021
7134  0.012441  0.001779          ya    0.143021
6940  0.012718  0.001779        went    0.139912
3887  0.052530  0.007117          ll    0.135494
2620  0.013824  0.001779        feel    0.128719
6460  0.013824  0.001779        told    0.128719
3050  0.014100  0.001779         gud    0.126195
1901  0.014929  0.001779         cos    0.119184
903   0.015206  0.001779         amp    0.117017
6165  0.015206  0.001779        sure    0.117017
4578  0.061100  0.007117          ok    0.116488
5475  0.016312  0.001779        said    0.109084
4289  0.016865  0.001779     morning    0.105507
3910  0.017694  0.001779         lol    0.100562
7149  0.017694  0.001779        yeah    0.100562
2259  0.019077  0.001779       doing    0.093275
1032  0.019630  0.001779         ask    0.090647
6891  0.019630  0.001779         way    0.090647
1794  0.048936  0.003559        come    0.072723
3762  0.030688  0.001779       later    0.057981
2015  0.032900  0.001779          da    0.054084
3932  0.032900  0.001779         lor    0.054084
3974  0.064142  0.001779          lt    0.027741
3044  0.064971  0.001779          gt    0.027387

[7204 rows x 4 columns]